if(NOT DEFINED BINARY OR NOT DEFINED CASE OR NOT DEFINED FIGURE4 OR
   NOT DEFINED WORK_DIR)
    message(FATAL_ERROR "BINARY, CASE, FIGURE4, and WORK_DIR are required")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")

function(run_ok)
    execute_process(COMMAND "${BINARY}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT "${status}" STREQUAL "0")
        message(FATAL_ERROR "Subcubic AA failed (${status}): ${errors}")
    endif()
    if(NOT errors STREQUAL "")
        message(FATAL_ERROR "Unexpected diagnostics: ${errors}")
    endif()
    set(last_output "${output}" PARENT_SCOPE)
endfunction()

function(run_error expected)
    execute_process(COMMAND "${BINARY}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT "${status}" STREQUAL "1")
        message(FATAL_ERROR "Expected a rejected input, got ${status}: ${output} ${errors}")
    endif()
    if(NOT errors MATCHES "${expected}")
        message(FATAL_ERROR "Expected '${expected}' in diagnostic: ${errors}")
    endif()
endfunction()

if(CASE STREQUAL "figure4")
    run_ok(--graph "${FIGURE4}" --query "a,*d" --json-stats)
    if(NOT last_output MATCHES "\"nodes\":10" OR
       NOT last_output MATCHES "\"memory_aliases\":7,\"value_aliases\":30" OR
       NOT last_output MATCHES "\"alias\":true")
        message(FATAL_ERROR "Wrong Figure 4 value result: ${last_output}")
    endif()
    run_ok("${FIGURE4}" --query "*d,e" --json-stats)
    if(NOT last_output MATCHES "\"alias\":true")
        message(FATAL_ERROR "Missing Figure 4 value pair: ${last_output}")
    endif()
    run_ok("${FIGURE4}" --query "a,e" --json-stats)
    if(NOT last_output MATCHES "\"alias\":false")
        message(FATAL_ERROR "Value aliases became transitive: ${last_output}")
    endif()
    run_ok("${FIGURE4}" --memory-only --query "b,*c" --print-aliases
        --json-stats)
    if(NOT last_output MATCHES "\"value_aliases\":null" OR
       NOT last_output MATCHES "\"value_aliases_computed\":false" OR
       NOT last_output MATCHES "\"relation\":\"memory\"" OR
       NOT last_output MATCHES "\"alias\":true")
        message(FATAL_ERROR "Wrong memory-only result: ${last_output}")
    endif()
    set(expected_aliases [=["aliases":[["*c","*c"],["*c","b"],["*d","*d"],["b","*c"],["b","b"],["c","c"],["d","d"]]]=])
    string(FIND "${last_output}" "${expected_aliases}" pairs_position)
    if(pairs_position EQUAL -1)
        message(FATAL_ERROR "Wrong memory-pair enumeration: ${last_output}")
    endif()
elseif(CASE STREQUAL "modes")
    file(READ "${FIGURE4}" graph)
    set(graph_path "${WORK_DIR}/disconnected.graph")
    file(WRITE "${graph_path}" "${graph}\nisolated isolated __lotus_node__\n")
    set(reference_pairs "")
    foreach(fast ON OFF)
        foreach(components ON OFF)
            set(options --json-stats --print-aliases)
            if(NOT fast)
                list(APPEND options --no-fast-sets)
            endif()
            if(NOT components)
                list(APPEND options --no-components)
            endif()
            run_ok("${graph_path}" ${options})
            if(NOT last_output MATCHES "\"memory_aliases\":7,\"value_aliases\":31")
                message(FATAL_ERROR "Wrong disconnected counts: ${last_output}")
            endif()
            string(REGEX MATCH "\"aliases\":\\[.*\\]" pairs "${last_output}")
            if(pairs STREQUAL "")
                message(FATAL_ERROR "No alias enumeration: ${last_output}")
            endif()
            if(reference_pairs STREQUAL "")
                set(reference_pairs "${pairs}")
            elseif(NOT reference_pairs STREQUAL pairs)
                message(FATAL_ERROR "Alias pairs differ with fast=${fast}, components=${components}")
            endif()
        endforeach()
    endforeach()
elseif(CASE STREQUAL "input_validation")
    set(graph_path "${WORK_DIR}/input.graph")
    file(WRITE "${graph_path}" "p cell d\n")
    run_error("bidirected PEG" "${graph_path}")
    run_ok("${graph_path}" --bidirectional --query "cell,cell" --relation memory)
    if(NOT last_output MATCHES "relation=memory alias=yes")
        message(FATAL_ERROR "Reverse-edge completion failed: ${last_output}")
    endif()
    file(WRITE "${graph_path}" "p cell dbar\n")
    run_error("bidirected PEG" "${graph_path}")
    file(WRITE "${graph_path}" "p field f_0\nfield p fbar_0\n")
    run_error("unsupported label" "${graph_path}" --bidirectional)
    file(WRITE "${graph_path}" "x y a\ny x abar\n")
    run_error("assignment|incoming" "${graph_path}")
elseif(CASE STREQUAL "options")
    run_error("incompatible" "${FIGURE4}" --memory-only --relation value)
    run_error("two nonempty vertex names" "${FIGURE4}" --query "a,")
    run_error("Unknown vertex" "${FIGURE4}" --query "absent,a")
    run_error("Unknown relation" "${FIGURE4}" --relation points-to)
    run_error("Multiple input graphs" "${FIGURE4}" --graph "${FIGURE4}")
    run_error("Missing value" --graph)
    run_error("input graph is required")
    run_ok(--help)
    if(NOT last_output MATCHES "OOPSLA 2014")
        message(FATAL_ERROR "Missing driver help: ${last_output}")
    endif()
elseif(CASE STREQUAL "json_names")
    set(special [=[p"\name]=])
    set(graph_path "${WORK_DIR}/names.graph")
    file(WRITE "${graph_path}" "&p ${special} d\n${special} &p dbar\n")
    run_ok("${graph_path}" --query "${special},${special}" --print-aliases
        --json-stats)
    string(FIND "${last_output}" [=["lhs":"p\"\\name"]=] escaped_position)
    if(escaped_position EQUAL -1 OR NOT last_output MATCHES "\"alias\":true")
        message(FATAL_ERROR "Vertex names were not JSON-escaped: ${last_output}")
    endif()
else()
    message(FATAL_ERROR "Unknown Subcubic AA CLI test case: ${CASE}")
endif()
